version: "3"

services:
  backend:
    build: ./api/yaya_backend
    volumes:
      - ./api/yaya_backend:/app
    ports:
      - 8000:8000
  frontend:
    build: ./client
    volumes:
      - ./client:/app
    command: 
      npm install 
    ports:
      - 3000:3000
    depends_on:
      - backend
      
